FROM ubuntu:latest

WORKDIR /test

RUN apt-get update && apt-get install -qq -y --no-install-recommends wget unzip && rm -rf /var/lib/apt/lists/*
RUN wget https://jenkins.openbmc.org/job/ci-openbmc/lastSuccessfulBuild/distro=ubuntu,label=docker-builder,target=romulus/artifact/openbmc/build/tmp/deploy/images/romulus/*zip*/romulus.zip
RUN unzip romulus.zip && rm romulus.zip
RUN apt-get purge -y --auto-remove wget

COPY test_in_docker.sh ./
COPY test_obmc1.py ./
RUN chmod +rx test_in_docker.sh
RUN chmod +rx test_obmc1.py
RUN apt-get update && apt-get -y install qemu-system-arm

# Set ENTRYPOINT to the script
ENTRYPOINT [ "./test_in_docker.sh" ]
