FROM ubuntu:latest

WORKDIR /test
RUN mkdir romulus
COPY romulus/ ./romulus/
COPY test_in_docker.sh ./
COPY test_obmc1.py ./
RUN chmod +rx test_in_docker.sh
RUN chmod +rx test_obmc1.py
RUN chmod +rx romulus
RUN apt-get update && apt-get -y install qemu-system-arm

RUN apt-get -y install wget
RUN apt-get -y install dpkg
RUN apt-get update && apt-get upgrade
RUN apt-get -y install fonts-liberation
RUN apt-get -y install xdg-utils
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb
RUN rm google-chrome-stable_current_amd64.deb

RUN apt-get -y install python3-venv python3-pip
RUN python3 -m venv obmc_venv
RUN . ./obmc_venv/bin/activate
RUN pip install --upgrade pip
RUN pip install requests pytest selenium

# Set ENTRYPOINT to the script
ENTRYPOINT [ "./test_in_docker.sh" ]
